export const readoutText = {
  title: "O-Tid – avläsning",
  noRace: "Ingen tävling vald. Öppna avläsningen från tävlingens administrationssida.",
  station: "Station",
  internet: "Internet",
  queue: "Kö",
  packageLabel: "Underlag",
  online: "Ansluten",
  offline: "Ej ansluten",
  queueEmpty: "0 väntar",
  queueWaiting: (count: number) => `${count} väntar`,
  packageMissing: "Saknas",
  packageVersion: (version: number, fetched: string) => `v${version} · hämtat ${fetched}`,
  stationStatus: {
    disconnected: "Ej ansluten",
    connecting: "Ansluter …",
    ready: (serial: number) => `Redo (nr ${serial})`,
    exercise: "Övningsstation",
    misconfigured: "Fel inställd",
    noResponse: "Svarar inte",
    error: "Fel"
  },
  connectSerial: "Anslut SPORTident-station",
  connectExercise: "Starta övningsstation",
  disconnect: "Koppla från station",
  serialUnsupported: "Den här webbläsaren kan inte ansluta USB-stationer. Använd Chrome eller Edge på dator.",
  serialFailed: "Stationen svarade inte. Kontrollera kabeln och att stationen är i avläsningsläge.",
  misconfiguredHelp: "Ställ stationen i läget avläsning (Readout) med utökat protokoll och anslut igen.",
  waitingForCard: "Sätt i brickan",
  reading: (card: number) => `Läser bricka ${card} …`,
  readFailed: (card: number) => `Bricka ${card} lästes inte färdigt. Sätt i den igen.`,
  unsupported: (card: number) => `Bricka ${card} har en typ som inte stöds.`,
  verdict: {
    OK: "GODKÄND",
    MP: "FELSTÄMPLAD",
    UNKNOWN_CARD: "OKÄND BRICKA",
    NO_PACKAGE: "SPARAD"
  },
  reason: {
    COMPLETE: "",
    MISSING_CONTROL: "Saknar kontroll",
    WRONG_ORDER: "Kontrollerna i fel ordning",
    MISSING_START: "Ingen starttid",
    MISSING_FINISH: "Ingen målstämpling",
    INVALID_TIME_ORDER: "Målet ligger före starten",
    UNKNOWN_CARD: "Brickan är inte kopplad till någon deltagare. Registrera den under Hantera tävling."
  } as Record<string, string>,
  missing: (codes: readonly number[]) => `Saknar: ${codes.join(", ")}`,
  // Gafflad bana (ADR-0169 beslut 2).
  variant: (code: string) => `Variant ${code}`,
  variantGuessed: (code: string) => `Variant ${code} (efter stämplingarna)`,
  // Stafett (ADR-0169 beslut 3).
  relayTeam: (number: number, name: string, leg: number, legCount: number) => `Lag ${number} ${name} · Sträcka ${leg} av ${legCount}`,
  relayNext: (leg: number) => `Växlar till sträcka ${leg}`,
  relayLast: "Sista sträckan",
  relayTeamTime: (time: string) => `Lagets tid ${time}`,
  relayTeamWaiting: "Lagets tid när alla sträckor är avlästa",
  relayTeamStatus: { OK: "Laget godkänt", MP: "Laget felstämplat", DSQ: "Laget diskat", DNF: "Laget har brutit", OOC: "Laget utom tävlan",
    NT: "Laget utan tidtagning", DNS: "Laget har en sträcka som inte startat", RUNNING: "" } as Record<string, string>,
  relayPlace: (teamNumber: number, leg: number) => `Lag ${teamNumber} · Sträcka ${leg}`,
  noPackage: "Inget tävlingsunderlag hämtat ännu. Avläsningen är sparad och bedöms av servern.",
  savedLocally: "Sparad i den här webbläsaren. Skickas när nätet finns.",
  confirmed: "Bekräftad av servern.",
  serverDiffers: (status: string) => `Servern bedömde avläsningen annorlunda: ${status}. Serverns bedömning gäller.`,
  splits: "Sträcktider",
  // Rogaining (ADR-0170 beslut 5).
  rogainingTotal: (total: number) => `${total} poäng`,
  rogainingBreakdown: (controlPoints: number, penalty: number) => penalty > 0
    ? `${controlPoints} p kontroller − ${penalty} p straff` : `${controlPoints} p kontroller · inget straff`,
  rogainingTime: (time: string, limit: string) => `Tid ${time} av ${limit}`,
  rogainingLate: (minutes: number) => `För sen: ${minutes} ${minutes === 1 ? "påbörjad minut" : "påbörjade minuter"} över tidsgränsen`,
  rogainingControls: "Räknade kontroller",
  rogainingPoints: (points: number) => `${points} p`,
  exerciseLate: "Läs av: för sen",
  rejected: (reason: string) => `Servern avvisade avläsningen (${reason}). Rådata finns kvar här.`,
  localInvalid: "Avläsningen kunde inte paketeras. Rådata finns kvar i den här webbläsaren.",
  recent: "Senaste avläsningar",
  none: "Inga avläsningar ännu.",
  statusPending: "Väntar",
  statusStored: "Skickad",
  statusDuplicate: "Redan mottagen",
  statusRejected: "Avvisad",
  exercise: "Övningsstation",
  exerciseHelp: "Skapar en bricka för vald deltagare och läser av den genom samma protokoll som en riktig station. Okänd bricka springer vald deltagares bana med ett oanmält bricknummer.",
  exerciseRunner: "Deltagare",
  exerciseNoRunners: "Inga deltagare med SPORTident-bricka i underlaget.",
  exerciseOk: "Läs av: rätt stämplat",
  exerciseMissing: "Läs av: missad kontroll",
  exerciseNoFinish: "Läs av: utan mål",
  exerciseUnknown: "Läs av: okänd bricka",
  loginNeeded: "Inloggningen har gått ut. Logga in igen för att skicka kön. Avläsningar sparas under tiden.",
  login: "Logga in",
  manage: "Hantera tävling",
  results: "Resultat",
  syncFailed: (status: number) => `Servern svarade ${status}. Kön ligger kvar och skickas igen.`,
  rawLog: "Ladda ner rålogg",
  rawLogHelp: "All trafik med stationen sedan sidan öppnades och råramarna för loppets avläsningar, utan namn. Skicka filen till utvecklaren om en station eller bricka beter sig fel.",
  // Kvitto och QR-kod (PLAN.md steg 21).
  receipt: {
    print: "Skriv ut kvitto",
    auto: "Skriv ut kvitto automatiskt",
    showQr: "Visa QR-kod för löparen",
    paper: "Kvittobredd",
    paperOption: (millimetres: number) => `${millimetres} mm`,
    preview: "Kvitto",
    close: "Dölj kvitto",
    region: "Kvitto",
    card: (card: string) => `Bricka ${card}`,
    columns: ["", "Kontroll", "Sträcka", "Tid"] as const,
    rogainingColumns: ["", "Kontroll", "Poäng", "Tid"] as const,
    finish: "Mål",
    time: "Tid",
    controlPoints: "Kontrollpoäng",
    penalty: "Straff",
    total: "Summa",
    timeOfLimit: (time: string, limit: string) => `${time} av ${limit}`,
    missing: (codes: readonly number[]) => `Saknar: ${codes.join(", ")}`,
    noSplits: "Inga sträcktider.",
    scan: "Skanna för dina resultat",
    notPublished: "Resultatsidan syns när tävlingen publiceras.",
    printedAt: (time: string) => `Utskrivet ${time}`,
    footer: "O-Tid"
  },
  storageNotPersistent: "Webbläsaren har inte lovat att spara kön beständigt. Töm inte webbläsardata under tävlingen."
} as const;
