buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21'
    }
}

apply from: 'variables.gradle'

allprojects {
    buildscript {
        configurations.configureEach {
            resolutionStrategy.force 'com.android.tools.build:gradle:8.13.2'
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencyLocking {
        lockAllConfigurations()
    }
}
