"use client";
import React, { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { didNotFinishWithdrawalAdminLoginRequestSchema, didNotFinishWithdrawalAdminLoginResponseSchema, type DidNotFinishWithdrawalResponse } from "@o-tid/contracts";
import { sv } from "../i18n/sv";
import { createDidNotFinishWithdrawalAttempt, isDefinitiveDidNotFinishWithdrawalRejection, parseDidNotFinishWithdrawalResponse, parseDidNotFinishWithdrawals, readDidNotFinishWithdrawalAdminCsrf, type DidNotFinishWithdrawalAttempt, type DidNotFinishWithdrawals } from "../lib/did-not-finish-withdrawal-admin-client";

type AttemptPhase = "CONFIRM" | "UNKNOWN" | "REAUTH";
type WithdrawalEntry = DidNotFinishWithdrawals["entries"][number];
async function responseJson(response: Response): Promise<unknown> { try { return await response.json() as unknown; } catch { throw new Error(sv.didNotFinishWithdrawalInvalidResponse); } }
function messageFrom(error: unknown): string {
  if (error instanceof TypeError) return sv.didNotFinishWithdrawalNetworkError;
  return error instanceof Error ? error.message : sv.didNotFinishWithdrawalUnknownError;
}

export function DidNotFinishWithdrawalAdmin({ raceId }: { raceId: string }) {
  const [accessCredential, setAccessCredential] = useState(""); const [authenticated, setAuthenticated] = useState<boolean>(); const [withdrawals, setWithdrawals] = useState<DidNotFinishWithdrawals>(); const [attempt, setAttempt] = useState<DidNotFinishWithdrawalAttempt>(); const [attemptPhase, setAttemptPhase] = useState<AttemptPhase>(); const [lastResult, setLastResult] = useState<DidNotFinishWithdrawalResponse>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>(sv.didNotFinishWithdrawalCheckingSession);
  const [online, setOnline] = useState<boolean>(); const confirmRef = useRef<HTMLHeadingElement>(null); const retryRef = useRef<HTMLHeadingElement>(null);
  const sessionUrl = `/api/admin/races/${raceId}/did-not-finish-withdrawal-session`; const listUrl = `/api/admin/races/${raceId}/did-not-finish-withdrawals`;
  const load = useCallback(async () => { const response = await fetch(listUrl, { credentials: "same-origin", cache: "no-store" }); if (response.status === 401 || response.status === 403) { setAuthenticated(false); setWithdrawals(undefined); setMessage(sv.didNotFinishWithdrawalLoginRequired); return false; } if (!response.ok) throw new Error(`${sv.didNotFinishWithdrawalSessionFailed} (${response.status})`); setWithdrawals(parseDidNotFinishWithdrawals(await responseJson(response), raceId)); setAuthenticated(true); setMessage(""); return true; }, [listUrl, raceId]);
  useEffect(() => { void load().catch((error: unknown) => { setWithdrawals(undefined); setMessage(messageFrom(error)); }); }, [load]);
  useEffect(() => { const updateOnline = () => setOnline(navigator.onLine); updateOnline(); window.addEventListener("online", updateOnline); window.addEventListener("offline", updateOnline); return () => { window.removeEventListener("online", updateOnline); window.removeEventListener("offline", updateOnline); }; }, []);
  useEffect(() => { if (!attempt || busy) return; const heading = attemptPhase === "CONFIRM" ? confirmRef.current : attemptPhase === "UNKNOWN" || attemptPhase === "REAUTH" ? retryRef.current : null; heading?.scrollIntoView({ block: "start" }); heading?.focus({ preventScroll: true }); }, [attempt, attemptPhase, busy]);

  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(sv.didNotFinishWithdrawalLoggingIn); try { const parsed = didNotFinishWithdrawalAdminLoginRequestSchema.safeParse({ formatVersion: 1, accessCredential }); if (!parsed.success) throw new Error(sv.didNotFinishWithdrawalLoginRejected); const response = await fetch(sessionUrl, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) }); if (!response.ok) throw new Error(response.status === 401 ? sv.didNotFinishWithdrawalLoginRejected : `${sv.didNotFinishWithdrawalSessionFailed} (${response.status})`); const session = didNotFinishWithdrawalAdminLoginResponseSchema.safeParse(await responseJson(response)); if (!session.success || session.data.raceId !== raceId || session.data.capability !== "WITHDRAW_DID_NOT_FINISH") throw new Error(sv.didNotFinishWithdrawalInvalidResponse); const loaded = await load(); if (loaded && attempt !== undefined) setMessage(sv.didNotFinishWithdrawalAttemptRetained); } catch (error) { setMessage(messageFrom(error)); } finally { setAccessCredential(""); setBusy(false); } }
  async function submit(current: DidNotFinishWithdrawalAttempt) { let csrf: string; try { csrf = readDidNotFinishWithdrawalAdminCsrf(document.cookie, new URL(window.location.href)); } catch (error) { setAuthenticated(false); setWithdrawals(undefined); setAttemptPhase("REAUTH"); setMessage(`${messageFrom(error)} ${sv.didNotFinishWithdrawalAttemptRetained}`); return; } setBusy(true); setMessage(sv.didNotFinishWithdrawalWorking); try { const response = await fetch(`/api/admin/races/${raceId}/entries/${current.entryId}/did-not-finish-withdrawal`, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "idempotency-key": `did-not-finish-withdrawal:${current.requestId}`, "x-otid-csrf": csrf }, body: JSON.stringify(current.request) }); if (!response.ok) { if (response.status === 401 || response.status === 403) { setAuthenticated(false); setWithdrawals(undefined); setAttemptPhase("REAUTH"); setMessage(`${sv.didNotFinishWithdrawalFailed} (${response.status}). ${sv.didNotFinishWithdrawalLoginAgain} ${sv.didNotFinishWithdrawalAttemptRetained}`); return; } if (isDefinitiveDidNotFinishWithdrawalRejection(response.status)) { setAttempt(undefined); setAttemptPhase(undefined); if (response.status === 409) try { await load(); } catch { setWithdrawals(undefined); } setMessage(response.status === 409 ? sv.didNotFinishWithdrawalConflict : `${sv.didNotFinishWithdrawalFailed} (${response.status}).`); return; } throw new Error(`${sv.didNotFinishWithdrawalFailed} (${response.status}). ${sv.didNotFinishWithdrawalUnknownCommitHelp}`); } const result = parseDidNotFinishWithdrawalResponse(await responseJson(response), current, raceId); setLastResult(result); setAttempt(undefined); setAttemptPhase(undefined); const success = result.replayed ? sv.didNotFinishWithdrawalReplayRecovered : sv.didNotFinishWithdrawalCreated; try { await load(); setMessage(success); } catch { setWithdrawals(undefined); setMessage(`${success} ${sv.didNotFinishWithdrawalSessionFailed}.`); } } catch (error) { setAttemptPhase("UNKNOWN"); setMessage(`${messageFrom(error)} ${sv.didNotFinishWithdrawalAttemptRetained}`); } finally { setBusy(false); } }
  function begin(candidate: WithdrawalEntry) { if (!withdrawals || candidate.state !== "WITHDRAWABLE") return; setLastResult(undefined); try { setAttempt(createDidNotFinishWithdrawalAttempt(candidate, withdrawals)); setAttemptPhase("CONFIRM"); setMessage(sv.didNotFinishWithdrawalConfirmHelp); } catch (error) { setMessage(messageFrom(error)); } }
  async function logout() { setBusy(true); try { const response = await fetch(sessionUrl, { method: "DELETE", credentials: "same-origin", headers: { "x-otid-csrf": readDidNotFinishWithdrawalAdminCsrf(document.cookie, new URL(window.location.href)) } }); if (!response.ok && response.status !== 401) throw new Error(`${sv.didNotFinishWithdrawalLogoutFailed} (${response.status})`); setAuthenticated(false); setWithdrawals(undefined); setLastResult(undefined); setMessage(attempt === undefined ? sv.didNotFinishWithdrawalLoggedOut : `${sv.didNotFinishWithdrawalLoggedOut} ${sv.didNotFinishWithdrawalAttemptRetained}`); } catch (error) { setMessage(messageFrom(error)); } finally { setAccessCredential(""); setBusy(false); } }
  const withdrawableCount = withdrawals?.entries.filter((entry) => entry.state === "WITHDRAWABLE").length ?? 0;

  return <div className="stack did-not-finish-withdrawal-admin">
    <div className="did-not-finish-withdrawal-state-strip" aria-label={sv.didNotFinishWithdrawalStateHeading}>
      <span><strong>{sv.didNotFinishWithdrawalInternetLabel}:</strong> {online === undefined ? sv.didNotFinishWithdrawalChecking : online ? sv.didNotFinishWithdrawalOnline : sv.didNotFinishWithdrawalOffline}</span>
      <span><strong>{sv.didNotFinishWithdrawalSessionLabel}:</strong> {authenticated === undefined ? sv.didNotFinishWithdrawalChecking : authenticated ? sv.didNotFinishWithdrawalSessionActive : sv.didNotFinishWithdrawalSessionRequired}</span>
      <span><strong>{sv.didNotFinishWithdrawalCountLabel}:</strong> {authenticated && withdrawals ? withdrawableCount : "–"}</span>
    </div>
    <section className="did-not-finish-withdrawal-security-note" aria-label={sv.didNotFinishWithdrawalSecurityHeading}><strong>{sv.didNotFinishWithdrawalSecurityHeading}.</strong> {sv.didNotFinishWithdrawalSecurityBoundary} <strong>{sv.didNotFinishWithdrawalActionWarning}</strong></section>
    {authenticated !== true && <form className="panel stack did-not-finish-withdrawal-login" onSubmit={(event) => void login(event)}><h2>{sv.didNotFinishWithdrawalLoginHeading}</h2><p className="muted">{sv.didNotFinishWithdrawalLoginHelp}</p><label>{sv.didNotFinishWithdrawalAccessCredential}<input type="password" autoComplete="off" spellCheck={false} value={accessCredential} onChange={(event) => setAccessCredential(event.target.value)} required /></label><button type="submit" disabled={busy || accessCredential.length === 0}>{sv.didNotFinishWithdrawalLogin}</button></form>}
    {authenticated === true && withdrawals && <section className="panel stack did-not-finish-withdrawal-data" aria-labelledby="did-not-finish-withdrawal-data-heading"><div className="did-not-finish-withdrawal-heading"><div><h2 id="did-not-finish-withdrawal-data-heading">{sv.didNotFinishWithdrawalDataHeading}</h2><p className="muted">{sv.didNotFinishWithdrawalDataHelp}</p><p className="did-not-finish-withdrawal-snapshot">{sv.didNotFinishWithdrawalSnapshotVersion}: <strong>{withdrawals.snapshotVersion}</strong></p></div><button type="button" className="secondary" disabled={busy} onClick={() => void logout()}>{sv.didNotFinishWithdrawalLogout}</button></div>
      <div className="did-not-finish-withdrawal-list"><div className="did-not-finish-withdrawal-list-head" aria-hidden="true"><span>{sv.didNotFinishWithdrawalParticipantHeading}</span><span>{sv.didNotFinishWithdrawalClass}</span><span>{sv.didNotFinishWithdrawalEntryVersion}</span><span>{sv.didNotFinishWithdrawalDecisionRevision}</span><span>{sv.didNotFinishWithdrawalAbsoluteHead}</span><span>{sv.didNotFinishWithdrawalSourceRevision}</span><span>{sv.didNotFinishWithdrawalStateLabel}</span><span>{sv.didNotFinishWithdrawalActionHeading}</span></div>
        {withdrawals.entries.map((candidate) => <article className="did-not-finish-withdrawal-entry" key={candidate.id}><div className="did-not-finish-withdrawal-person"><h3>{candidate.displayName}</h3><p>{candidate.organisationName ?? "–"}</p></div><p><span className="did-not-finish-withdrawal-mobile-label">{sv.didNotFinishWithdrawalClass}: </span>{candidate.className}</p><p><span className="did-not-finish-withdrawal-mobile-label">{sv.didNotFinishWithdrawalEntryVersion}: </span>{candidate.entryVersion}</p><p><span className="did-not-finish-withdrawal-mobile-label">{sv.didNotFinishWithdrawalDecisionRevision}: </span>{candidate.didNotFinishResultRevision.revision}</p><p><span className="did-not-finish-withdrawal-mobile-label">{sv.didNotFinishWithdrawalAbsoluteHead}: </span>{candidate.absoluteResultRevision.revision}</p><p className="did-not-finish-withdrawal-source"><span className="did-not-finish-withdrawal-mobile-label">{sv.didNotFinishWithdrawalSourceRevision}: </span>{candidate.restorationSourceResultRevision.revision} · {candidate.restorationSourceResultRevision.status}<small>{sv.publicResultsReasonLabels[candidate.restorationSourceResultRevision.reason]}</small></p><p className="did-not-finish-withdrawal-state"><strong>{candidate.state === "WITHDRAWABLE" ? sv.didNotFinishWithdrawalWithdrawable : sv.didNotFinishWithdrawalWithdrawn}</strong></p><button type="button" disabled={busy || attempt !== undefined || candidate.state !== "WITHDRAWABLE"} onClick={() => begin(candidate)}>{sv.didNotFinishWithdrawalBegin}</button></article>)}
        {withdrawals.entries.length === 0 && <p className="did-not-finish-withdrawal-empty muted">{sv.didNotFinishWithdrawalNoEntries}</p>}</div></section>}
    {attempt && attemptPhase === "CONFIRM" && <section className="panel did-not-finish-withdrawal-confirm stack" role="alert"><h2 ref={confirmRef} tabIndex={-1}>△ {sv.didNotFinishWithdrawalConfirmHeading}</h2><p>{sv.didNotFinishWithdrawalConfirmWarning}</p><dl><dt>{sv.didNotFinishWithdrawalPendingEntry}</dt><dd>{attempt.displayName}</dd><dt>{sv.didNotFinishWithdrawalClass}</dt><dd>{attempt.className}</dd><dt>{sv.didNotFinishWithdrawalAbsoluteHead}</dt><dd>{attempt.request.expectedAbsoluteResultRevision.revision}</dd><dt>{sv.didNotFinishWithdrawalPendingSource}</dt><dd>{attempt.request.expectedRestorationSourceResultRevision.revision} · {attempt.request.expectedRestorationSourceResultRevision.status} · {sv.publicResultsReasonLabels[attempt.request.expectedRestorationSourceResultRevision.reason]}</dd><dt>{sv.didNotFinishWithdrawalPendingSnapshot}</dt><dd>{attempt.request.expectedSnapshotVersion}</dd></dl><div className="pairing-actions"><button type="button" disabled={busy} onClick={() => void submit(attempt)}>{sv.didNotFinishWithdrawalConfirm}</button><button type="button" className="secondary danger" disabled={busy} onClick={() => { setAttempt(undefined); setAttemptPhase(undefined); setMessage(""); }}>{sv.didNotFinishWithdrawalCancel}</button></div></section>}
    {attempt && (attemptPhase === "UNKNOWN" || attemptPhase === "REAUTH") && <section className="panel did-not-finish-withdrawal-retry stack" role="alert"><h2 ref={retryRef} tabIndex={-1}>△ {attemptPhase === "UNKNOWN" ? sv.didNotFinishWithdrawalUnknownCommit : sv.didNotFinishWithdrawalLoginRequired}</h2><p>{attemptPhase === "UNKNOWN" ? sv.didNotFinishWithdrawalUnknownCommitHelp : sv.didNotFinishWithdrawalLoginAgain}</p><dl><dt>{sv.didNotFinishWithdrawalPendingEntry}</dt><dd>{attempt.displayName}</dd><dt>{sv.didNotFinishWithdrawalPendingRequest}</dt><dd className="pairing-grant-id">{attempt.requestId}</dd><dt>{sv.didNotFinishWithdrawalAbsoluteHead}</dt><dd>{attempt.request.expectedAbsoluteResultRevision.revision}</dd><dt>{sv.didNotFinishWithdrawalPendingSource}</dt><dd>{attempt.request.expectedRestorationSourceResultRevision.revision} · {attempt.request.expectedRestorationSourceResultRevision.status} · {sv.publicResultsReasonLabels[attempt.request.expectedRestorationSourceResultRevision.reason]}</dd></dl><div className="pairing-actions">{authenticated === true && <button type="button" disabled={busy} onClick={() => void submit(attempt)}>{sv.didNotFinishWithdrawalRetrySame}</button>}<button type="button" className="secondary danger" disabled={busy} onClick={() => { setAttempt(undefined); setAttemptPhase(undefined); setMessage(""); }}>{sv.didNotFinishWithdrawalClearAttempt}</button></div></section>}
    {lastResult && <section className="panel did-not-finish-withdrawal-result" aria-label={sv.didNotFinishWithdrawalCreated}><p><strong>✓ {lastResult.replayed ? sv.didNotFinishWithdrawalReplayRecovered : sv.didNotFinishWithdrawalCreated}</strong></p><p>{sv.didNotFinishWithdrawalId}: <span className="pairing-grant-id">{lastResult.didNotFinishWithdrawalId}</span></p></section>}<p className="pairing-message" role="status" aria-live="polite">{message}</p>
  </div>;
}
