"use client";
import React, { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { outOfCompetitionWithdrawalAdminLoginRequestSchema, outOfCompetitionWithdrawalAdminLoginResponseSchema, type OutOfCompetitionWithdrawalResponse } from "@o-tid/contracts";
import { sv } from "../i18n/sv";
import { createOutOfCompetitionWithdrawalAttempt, isDefinitiveOutOfCompetitionWithdrawalRejection, parseOutOfCompetitionWithdrawalResponse, parseOutOfCompetitionWithdrawals, readOutOfCompetitionWithdrawalAdminCsrf, type OutOfCompetitionWithdrawalAttempt, type OutOfCompetitionWithdrawals } from "../lib/out-of-competition-withdrawal-admin-client";

type AttemptPhase = "CONFIRM" | "UNKNOWN" | "REAUTH";
type Candidate = OutOfCompetitionWithdrawals["entries"][number];
async function responseJson(response: Response): Promise<unknown> { try { return await response.json() as unknown; } catch { throw new Error(sv.outOfCompetitionWithdrawalInvalidResponse); } }
function messageFrom(error: unknown): string { return error instanceof Error ? error.message : sv.outOfCompetitionWithdrawalUnknownError; }
function stateText(value: Candidate["state"]): string { return value === "WITHDRAWABLE" ? `✓ ${sv.outOfCompetitionWithdrawalWithdrawable}` : `△ ${sv.outOfCompetitionWithdrawalWithdrawn}`; }

function FrozenProvenance({ attempt, showRequestId = false }: { attempt: OutOfCompetitionWithdrawalAttempt; showRequestId?: boolean }) {
  const request = attempt.request;
  return <dl className="out-of-competition-withdrawal-provenance">
    <dt>{sv.outOfCompetitionWithdrawalPendingEntry}</dt><dd>{attempt.displayName}</dd>
    <dt>{sv.outOfCompetitionWithdrawalClass}</dt><dd>{attempt.className}</dd>
    <dt>{sv.outOfCompetitionWithdrawalEntryVersion}</dt><dd>{request.expectedEntryVersion}</dd>
    <dt>{sv.outOfCompetitionWithdrawalDecision}</dt><dd className="pairing-grant-id">{request.expectedNotCompetingDecisionId}</dd>
    <dt>{sv.outOfCompetitionWithdrawalDecisionRevision}</dt><dd>{request.expectedOutOfCompetitionResultRevision.revision}</dd>
    <dt>{sv.outOfCompetitionWithdrawalAbsoluteHead}</dt><dd>{request.expectedAbsoluteResultRevision.revision}</dd>
    <dt>{sv.outOfCompetitionWithdrawalPendingSource}</dt><dd>{request.expectedRestorationSourceResultRevision.revision} · {request.expectedRestorationSourceResultRevision.status}<small>{sv.publicResultsReasonLabels[request.expectedRestorationSourceResultRevision.reason]}</small></dd>
    <dt>{sv.outOfCompetitionWithdrawalPendingSnapshot}</dt><dd>{request.expectedSnapshotVersion}</dd>
    {showRequestId && <><dt>{sv.outOfCompetitionWithdrawalPendingRequest}</dt><dd className="pairing-grant-id">{attempt.requestId}</dd></>}
  </dl>;
}

export function OutOfCompetitionWithdrawalAdmin({ raceId }: { raceId: string }) {
  const [accessCredential, setAccessCredential] = useState(""); const [authenticated, setAuthenticated] = useState<boolean>(); const [withdrawals, setWithdrawals] = useState<OutOfCompetitionWithdrawals>(); const [attempt, setAttempt] = useState<OutOfCompetitionWithdrawalAttempt>(); const [attemptPhase, setAttemptPhase] = useState<AttemptPhase>(); const [lastResult, setLastResult] = useState<OutOfCompetitionWithdrawalResponse>(); const [busy, setBusy] = useState(false); const [online, setOnline] = useState<boolean>(); const [message, setMessage] = useState<string>(sv.outOfCompetitionWithdrawalCheckingSession);
  const confirmRef = useRef<HTMLHeadingElement>(null); const retryRef = useRef<HTMLHeadingElement>(null);
  const sessionUrl = `/api/admin/races/${raceId}/out-of-competition-withdrawal-session`; const listUrl = `/api/admin/races/${raceId}/out-of-competition-withdrawals`;
  const load = useCallback(async () => { const response = await fetch(listUrl, { credentials: "same-origin", cache: "no-store" }); if (response.status === 401 || response.status === 403) { setAuthenticated(false); setWithdrawals(undefined); setMessage(sv.outOfCompetitionWithdrawalLoginRequired); return false; } if (!response.ok) throw new Error(`${sv.outOfCompetitionWithdrawalSessionFailed} (${response.status})`); setWithdrawals(parseOutOfCompetitionWithdrawals(await responseJson(response), raceId)); setAuthenticated(true); setMessage(""); return true; }, [listUrl, raceId]);
  useEffect(() => { void load().catch((error: unknown) => { setWithdrawals(undefined); setMessage(messageFrom(error)); }); }, [load]);
  useEffect(() => { const updateOnline = () => setOnline(navigator.onLine); updateOnline(); window.addEventListener("online", updateOnline); window.addEventListener("offline", updateOnline); return () => { window.removeEventListener("online", updateOnline); window.removeEventListener("offline", updateOnline); }; }, []);
  useEffect(() => { if (!attempt || busy) return; const heading = attemptPhase === "CONFIRM" ? confirmRef.current : attemptPhase === "UNKNOWN" || attemptPhase === "REAUTH" ? retryRef.current : null; heading?.scrollIntoView({ block: "start" }); heading?.focus({ preventScroll: true }); }, [attempt, attemptPhase, busy]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(sv.outOfCompetitionWithdrawalLoggingIn); try { const parsed = outOfCompetitionWithdrawalAdminLoginRequestSchema.safeParse({ formatVersion: 1, accessCredential }); if (!parsed.success) throw new Error(sv.outOfCompetitionWithdrawalLoginRejected); const response = await fetch(sessionUrl, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) }); if (!response.ok) throw new Error(response.status === 401 ? sv.outOfCompetitionWithdrawalLoginRejected : `${sv.outOfCompetitionWithdrawalSessionFailed} (${response.status})`); const session = outOfCompetitionWithdrawalAdminLoginResponseSchema.safeParse(await responseJson(response)); if (!session.success || session.data.raceId !== raceId || session.data.capability !== "WITHDRAW_OUT_OF_COMPETITION") throw new Error(sv.outOfCompetitionWithdrawalInvalidResponse); const loaded = await load(); if (loaded && attempt !== undefined) setMessage(sv.outOfCompetitionWithdrawalAttemptRetained); } catch (error) { setMessage(messageFrom(error)); } finally { setAccessCredential(""); setBusy(false); } }
  async function submit(current: OutOfCompetitionWithdrawalAttempt) { let csrf: string; try { csrf = readOutOfCompetitionWithdrawalAdminCsrf(document.cookie, new URL(window.location.href)); } catch (error) { setAuthenticated(false); setWithdrawals(undefined); setAttemptPhase("REAUTH"); setMessage(`${messageFrom(error)} ${sv.outOfCompetitionWithdrawalAttemptRetained}`); return; } setBusy(true); setMessage(sv.outOfCompetitionWithdrawalWorking); try { const response = await fetch(`/api/admin/races/${raceId}/entries/${current.entryId}/out-of-competition-withdrawal`, { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "idempotency-key": `out-of-competition-withdrawal:${current.requestId}`, "x-otid-csrf": csrf }, body: JSON.stringify(current.request) }); if (!response.ok) { if (response.status === 401 || response.status === 403) { setAuthenticated(false); setWithdrawals(undefined); setAttemptPhase("REAUTH"); setMessage(`${sv.outOfCompetitionWithdrawalFailed} (${response.status}). ${sv.outOfCompetitionWithdrawalLoginAgain} ${sv.outOfCompetitionWithdrawalAttemptRetained}`); return; } if (isDefinitiveOutOfCompetitionWithdrawalRejection(response.status)) { setAttempt(undefined); setAttemptPhase(undefined); if (response.status === 409) try { await load(); } catch { setWithdrawals(undefined); } setMessage(response.status === 409 ? sv.outOfCompetitionWithdrawalConflict : `${sv.outOfCompetitionWithdrawalFailed} (${response.status}).`); return; } throw new Error(`${sv.outOfCompetitionWithdrawalFailed} (${response.status}). ${sv.outOfCompetitionWithdrawalUnknownCommitHelp}`); } const result = parseOutOfCompetitionWithdrawalResponse(await responseJson(response), current, raceId); setLastResult(result); setAttempt(undefined); setAttemptPhase(undefined); const success = result.replayed ? sv.outOfCompetitionWithdrawalReplayRecovered : sv.outOfCompetitionWithdrawalCreated; try { await load(); setMessage(success); } catch { setWithdrawals(undefined); setMessage(`${success} ${sv.outOfCompetitionWithdrawalSessionFailed}.`); } } catch (error) { setAttemptPhase("UNKNOWN"); setMessage(`${messageFrom(error)} ${sv.outOfCompetitionWithdrawalAttemptRetained}`); } finally { setBusy(false); } }
  function begin(candidate: Candidate) { if (!withdrawals || candidate.state !== "WITHDRAWABLE") return; setLastResult(undefined); try { setAttempt(createOutOfCompetitionWithdrawalAttempt(candidate, withdrawals)); setAttemptPhase("CONFIRM"); setMessage(sv.outOfCompetitionWithdrawalConfirmHelp); } catch (error) { setMessage(messageFrom(error)); } }
  async function logout() { setBusy(true); try { const response = await fetch(sessionUrl, { method: "DELETE", credentials: "same-origin", headers: { "x-otid-csrf": readOutOfCompetitionWithdrawalAdminCsrf(document.cookie, new URL(window.location.href)) } }); if (!response.ok && response.status !== 401) throw new Error(`${sv.outOfCompetitionWithdrawalLogoutFailed} (${response.status})`); setAuthenticated(false); setWithdrawals(undefined); setLastResult(undefined); setMessage(attempt === undefined ? sv.outOfCompetitionWithdrawalLoggedOut : `${sv.outOfCompetitionWithdrawalLoggedOut} ${sv.outOfCompetitionWithdrawalAttemptRetained}`); } catch (error) { setMessage(messageFrom(error)); } finally { setAccessCredential(""); setBusy(false); } }
  const readyCount = withdrawals?.entries.filter((candidate) => candidate.state === "WITHDRAWABLE").length ?? 0;
  return <div className="stack out-of-competition-withdrawal-admin">
    <div className="out-of-competition-withdrawal-state-strip" aria-label={sv.outOfCompetitionWithdrawalStateHeading}>
      <span><strong>{sv.outOfCompetitionWithdrawalInternetLabel}:</strong> {online === undefined ? sv.outOfCompetitionWithdrawalChecking : online ? sv.outOfCompetitionWithdrawalOnline : sv.outOfCompetitionWithdrawalOffline}</span>
      <span><strong>{sv.outOfCompetitionWithdrawalSessionLabel}:</strong> {authenticated === undefined ? sv.outOfCompetitionWithdrawalChecking : authenticated ? sv.outOfCompetitionWithdrawalSessionActive : sv.outOfCompetitionWithdrawalSessionRequired}</span>
      <span><strong>{sv.outOfCompetitionWithdrawalReadyCountLabel}:</strong> {authenticated && withdrawals ? readyCount : "–"}</span>
    </div>
    <section className="out-of-competition-withdrawal-security-note" aria-label={sv.outOfCompetitionWithdrawalSecurityHeading}><strong>{sv.outOfCompetitionWithdrawalSecurityHeading}.</strong> {sv.outOfCompetitionWithdrawalSecurityBoundary} <strong>{sv.outOfCompetitionWithdrawalActionWarning}</strong></section>
    {authenticated !== true && <form className="panel stack out-of-competition-withdrawal-login" onSubmit={(event) => void login(event)}><h2>{sv.outOfCompetitionWithdrawalLoginHeading}</h2><p className="muted">{sv.outOfCompetitionWithdrawalLoginHelp}</p><label>{sv.outOfCompetitionWithdrawalAccessCredential}<input type="password" autoComplete="off" spellCheck={false} value={accessCredential} onChange={(event) => setAccessCredential(event.target.value)} required /></label><button type="submit" disabled={busy || accessCredential.length === 0}>{sv.outOfCompetitionWithdrawalLogin}</button></form>}
    {authenticated === true && withdrawals && <section className="panel stack out-of-competition-withdrawal-data" aria-labelledby="out-of-competition-withdrawal-data-heading"><div className="out-of-competition-withdrawal-heading"><div><h2 id="out-of-competition-withdrawal-data-heading">{sv.outOfCompetitionWithdrawalDataHeading}</h2><p className="muted">{sv.outOfCompetitionWithdrawalDataHelp}</p><p className="out-of-competition-withdrawal-snapshot">{sv.outOfCompetitionWithdrawalSnapshotVersion}: <strong>{withdrawals.snapshotVersion}</strong></p></div><button type="button" className="secondary" disabled={busy} onClick={() => void logout()}>{sv.outOfCompetitionWithdrawalLogout}</button></div><div className="out-of-competition-withdrawal-list">
      <div className="out-of-competition-withdrawal-list-head" aria-hidden="true"><span>{sv.outOfCompetitionWithdrawalParticipantHeading}</span><span>{sv.outOfCompetitionWithdrawalClass}</span><span>{sv.outOfCompetitionWithdrawalEntryVersion}</span><span>{sv.outOfCompetitionWithdrawalDecisionRevision}</span><span>{sv.outOfCompetitionWithdrawalAbsoluteHead}</span><span>{sv.outOfCompetitionWithdrawalSourceRevision}</span><span>{sv.outOfCompetitionWithdrawalStatusHeading}</span><span>{sv.outOfCompetitionWithdrawalActionHeading}</span></div>
      {withdrawals.entries.map((candidate) => <article className="out-of-competition-withdrawal-entry" key={candidate.id}>
        <div className="out-of-competition-withdrawal-person"><h3>{candidate.displayName}</h3><p>{candidate.organisationName ?? "–"}</p></div>
        <p><span className="out-of-competition-withdrawal-mobile-label">{sv.outOfCompetitionWithdrawalClass}: </span>{candidate.className}</p>
        <p><span className="out-of-competition-withdrawal-mobile-label">{sv.outOfCompetitionWithdrawalEntryVersion}: </span>{candidate.entryVersion}</p>
        <p><span className="out-of-competition-withdrawal-mobile-label">{sv.outOfCompetitionWithdrawalDecisionRevision}: </span>{candidate.outOfCompetitionResultRevision.revision}</p>
        <p><span className="out-of-competition-withdrawal-mobile-label">{sv.outOfCompetitionWithdrawalAbsoluteHead}: </span>{candidate.absoluteResultRevision.revision}</p>
        <p className="out-of-competition-withdrawal-source"><span className="out-of-competition-withdrawal-mobile-label">{sv.outOfCompetitionWithdrawalSourceRevision}: </span>{candidate.restorationSourceResultRevision.revision} · {candidate.restorationSourceResultRevision.status}<small>{sv.publicResultsReasonLabels[candidate.restorationSourceResultRevision.reason]}</small></p>
        <p className="out-of-competition-withdrawal-status"><strong>{stateText(candidate.state)}</strong></p>
        <button type="button" disabled={busy || attempt !== undefined || candidate.state !== "WITHDRAWABLE"} onClick={() => begin(candidate)}>{sv.outOfCompetitionWithdrawalBegin}</button>
      </article>)}
      {withdrawals.entries.length === 0 && <p className="out-of-competition-withdrawal-empty muted">{sv.outOfCompetitionWithdrawalNoEntries}</p>}
    </div></section>}
    {attempt && attemptPhase === "CONFIRM" && <section className="panel out-of-competition-withdrawal-confirm stack" role="alert"><h2 ref={confirmRef} tabIndex={-1}>△ {sv.outOfCompetitionWithdrawalConfirmHeading}</h2><p>{sv.outOfCompetitionWithdrawalConfirmHelp}</p><p><strong>{sv.outOfCompetitionWithdrawalConfirmWarning}</strong></p><FrozenProvenance attempt={attempt} /><div className="pairing-actions"><button type="button" disabled={busy} onClick={() => void submit(attempt)}>{sv.outOfCompetitionWithdrawalConfirm}</button><button type="button" className="secondary danger" disabled={busy} onClick={() => { setAttempt(undefined); setAttemptPhase(undefined); setMessage(""); }}>{sv.outOfCompetitionWithdrawalCancel}</button></div></section>}
    {attempt && (attemptPhase === "UNKNOWN" || attemptPhase === "REAUTH") && <section className="panel out-of-competition-withdrawal-retry stack" role="alert"><h2 ref={retryRef} tabIndex={-1}>△ {attemptPhase === "UNKNOWN" ? sv.outOfCompetitionWithdrawalUnknownCommit : sv.outOfCompetitionWithdrawalLoginRequired}</h2><p>{attemptPhase === "UNKNOWN" ? sv.outOfCompetitionWithdrawalUnknownCommitHelp : sv.outOfCompetitionWithdrawalLoginAgain}</p><FrozenProvenance attempt={attempt} showRequestId /><div className="pairing-actions">{authenticated === true && <button type="button" disabled={busy} onClick={() => void submit(attempt)}>{sv.outOfCompetitionWithdrawalRetrySame}</button>}<button type="button" className="secondary danger" disabled={busy} onClick={() => { setAttempt(undefined); setAttemptPhase(undefined); setMessage(""); }}>{sv.outOfCompetitionWithdrawalClearAttempt}</button></div></section>}
    {lastResult && <section className="panel out-of-competition-withdrawal-result" aria-label={sv.outOfCompetitionWithdrawalCreated}><p><strong>✓ {lastResult.replayed ? sv.outOfCompetitionWithdrawalReplayRecovered : sv.outOfCompetitionWithdrawalCreated}</strong></p><p>{sv.outOfCompetitionWithdrawalId}: <span className="pairing-grant-id">{lastResult.outOfCompetitionWithdrawalId}</span></p><p>{sv.outOfCompetitionWithdrawalRestoredRevision}: <span className="pairing-grant-id">{lastResult.restorationResultRevisionId}</span></p></section>}
    <p className="pairing-message" role="status" aria-live="polite">{message}</p>
  </div>;
}
