import { createHash, randomUUID } from "node:crypto";
import { afterAll, beforeAll, expect, it } from "vitest";
import { migrate } from "@o-tid/database";
import { createDatabase } from "@o-tid/database";
import { issuePairingAdminAccessCredential, loginPairingAdmin } from "../../src/pairing-admin";
import { issueRouteUploadGrantAsAdmin } from "../../src/route-upload-grant";
import { redeemRouteUploadBearerLink, routeUploadBearerTokenPrefix } from "../../src/route-upload-session";
import { reserveRouteUploadAsParticipant, transferRouteUploadAsParticipant } from "../../src/route-upload";
import { decideRoutePublicationConsentAsParticipant, readRoutePublicationConsentAsParticipant } from "../../src/route-publication-consent";

const url = process.env.TEST_DATABASE_URL;
if (!url) throw new Error("TEST_DATABASE_URL krävs för en uttryckligen isolerad testdatabas");
const { db, pool } = createDatabase(url);
const now = new Date("2026-09-21T20:00:00.000Z");
const gpx = Buffer.from('<?xml version="1.0"?><gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1" creator="O-Tid"><trk><trkseg><trkpt lat="59.321" lon="18.071"><time>2026-09-21T10:00:00Z</time></trkpt><trkpt lat="59.322" lon="18.072"><time>2026-09-21T10:01:00Z</time></trkpt></trkseg></trk></gpx>');
const sha256 = createHash("sha256").update(gpx).digest("hex");
beforeAll(async () => migrate(db, { migrationsFolder: new URL("../../../database/migrations", import.meta.url).pathname }));
afterAll(async () => pool.end());
async function* body(): AsyncIterable<Uint8Array> { yield gpx; }

it("TASK116 journals participant grant and withdrawal for only the current immutable private route", async () => {
  const eventId = randomUUID(), raceId = randomUUID(), courseId = randomUUID(), versionId = randomUUID(), classId = randomUUID(), entryId = randomUUID();
  await pool.query("INSERT INTO event(id,name,starts_on,time_zone) VALUES($1,'TASK116','2026-09-21','Europe/Stockholm')", [eventId]);
  await pool.query("INSERT INTO race(id,event_id,name,race_date) VALUES($1,$2,'TASK116','2026-09-21')", [raceId, eventId]);
  await pool.query("INSERT INTO course(id,race_id,name) VALUES($1,$2,'TASK116')", [courseId, raceId]);
  await pool.query("INSERT INTO course_version(id,course_id,version) VALUES($1,$2,1)", [versionId, courseId]);
  await pool.query("INSERT INTO class(id,race_id,name,course_version_id,start_rule) VALUES($1,$2,'Öppen',$3,'PUNCH')", [classId, raceId, versionId]);
  await pool.query("INSERT INTO entry(id,race_id,class_id,given_name,family_name) VALUES($1,$2,$3,'Ada','Consent')", [entryId, raceId, classId]);
  const credential = await issuePairingAdminAccessCredential(db, { raceId, capability: "MANAGE_RACE", label: "TASK116", expiresAt: new Date(now.getTime() + 3_600_000) }, { now });
  const login = await loginPairingAdmin(db, { formatVersion: 1, accessCredential: credential.accessCredential }, { expectedRaceId: raceId, expectedCapability: "MANAGE_RACE", now });
  if (login.status !== "authenticated") throw new Error("Synthetic administrator login failed");
  const admin = { raceId, sessionToken: login.sessionToken, csrfCookie: login.csrfToken, csrfHeader: login.csrfToken };
  const grantId = randomUUID(), secret = Buffer.alloc(32, 7);
  const grant = await issueRouteUploadGrantAsAdmin(db, { ...admin, idempotencyKey: `route-upload-grant:${randomUUID()}`, request: { formatVersion: 1, grantId, entryId, secretHash: createHash("sha256").update(secret).digest("hex"), expiresAt: new Date(now.getTime() + 3_600_000).toISOString() } }, now);
  if (grant.status !== "issued") throw new Error("Synthetic route grant failed");
  const redemption = await redeemRouteUploadBearerLink(db, `${routeUploadBearerTokenPrefix}.${grantId}.${secret.toString("base64url")}`, now);
  if (redemption.status !== "redeemed") throw new Error("Synthetic route redemption failed");
  const participant = { sessionToken: redemption.sessionToken, csrfCookie: redemption.csrfToken, csrfHeader: redemption.csrfToken };
  expect(await readRoutePublicationConsentAsParticipant(db, participant, now)).toEqual({ status: "ok", response: { formatVersion: 1, status: "not-uploaded" } });
  expect((await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${randomUUID()}`, request: { formatVersion: 1, decision: "GRANT" } }, now)).status).toBe("not-found");
  const reserve = await reserveRouteUploadAsParticipant(db, { ...participant, idempotencyKey: `route-upload:${randomUUID()}`, request: { formatVersion: 1, fileName: "ada.gpx", mediaType: "application/gpx+xml", byteLength: gpx.byteLength, sha256 } }, now);
  if (reserve.status !== "reserved") throw new Error("Synthetic route reservation failed");
  const upload = await transferRouteUploadAsParticipant(db, { ...participant, uploadId: reserve.response.uploadId, readBody: () => body() }, { async put(input) { return { formatVersion: 1, storeId: randomUUID(), key: `route/${input.raceId}/${input.attemptId}`, versionId: "synthetic-v1", mediaType: input.mediaType, sha256: input.sha256, byteLength: input.byteLength }; } }, () => now);
  expect(upload.status).toBe("stored");
  const requestId = randomUUID(), intent = { formatVersion: 1 as const, decision: "GRANT" as const };
  const granted = await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${requestId}`, request: intent }, now);
  expect(granted).toMatchObject({ status: "stored", response: { consent: "READY_FOR_FUTURE_PUBLICATION", revision: 1, replayed: false } });
  expect(await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${requestId}`, request: intent }, now)).toMatchObject({ status: "stored", response: { consent: "READY_FOR_FUTURE_PUBLICATION", revision: 1, replayed: true } });
  expect((await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${requestId}`, request: { formatVersion: 1, decision: "WITHDRAW" } }, now)).status).toBe("conflict");
  const withdrawn = await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${randomUUID()}`, request: { formatVersion: 1, decision: "WITHDRAW" } }, now);
  expect(withdrawn).toMatchObject({ status: "stored", response: { consent: "PRIVATE", revision: 2 } });
  expect(await readRoutePublicationConsentAsParticipant(db, participant, now)).toMatchObject({ status: "ok", response: { status: "stored", consent: "PRIVATE", revision: 2 } });
  expect((await decideRoutePublicationConsentAsParticipant(db, { ...participant, idempotencyKey: `route-publication-consent:${randomUUID()}`, request: intent }, new Date(now.getTime() + 7_200_000))).status).toBe("unauthorized");
  expect((await pool.query<{ count: number }>("SELECT count(*)::int AS count FROM route_publication_consent WHERE race_id=$1", [raceId])).rows).toEqual([{ count: 2 }]);
});
