export const sv = {
  static: {
    pageTitle: "O-Tid Deltagare",
    eyebrow: "O-TID · DELTAGARE",
    heading: "Privat GPS-inspelning",
    lead: "Utvecklarversion. Spåret sparas bara på den här telefonen; kontokoppling och synk finns ännu inte.",
    stateLabel: "Inspelning",
    loadingTitle: "Läser lokalt tillstånd…",
    loadingDetail: "Vänta medan appen frågar Androidtjänsten.",
    factsLabel: "Lokalt spår",
    pointLabel: "Punkter på telefonen",
    lastFixLabel: "Senaste mätning",
    recordingLabel: "Lokal version",
    networkLabel: "Nätverk",
    startAction: "Starta inspelning",
    resumeAction: "Fortsätt efter avbrott",
    stopAction: "Stoppa och spara",
    refreshAction: "Uppdatera status",
    privacyTitle: "Endast lokalt i denna version.",
    privacyDetail: "Avinstallation kan radera osynkade spår. GPS ger inte officiell tid, kontrollpassage eller information om vem som är kvar i skogen.",
    footer: "Utvecklarversion 0.1.0 · ingen uppladdning eller publicering"
  },
  state: {
    IDLE: { tone: "neutral", title: "Ingen inspelning pågår", detail: "Starta uttryckligen när du är redo. Spåret stannar på telefonen." },
    STARTING: { tone: "warning", title: "Startar GPS-tjänsten", detail: "Vänta på bekräftelse från Android innan du går iväg." },
    WAITING_FIX: { tone: "warning", title: "GPS aktiv – väntar på position", detail: "Tjänsten körs, men ingen färsk GPS-punkt har sparats ännu." },
    RECORDING: { tone: "ready", title: "GPS-punkter sparas lokalt", detail: "Kontrollera att antalet punkter fortsätter öka under loppet." },
    INTERRUPTED: { tone: "error", title: "Inspelningen avbröts", detail: "Tidigare punkter finns kvar. En lucka kan ha uppstått; fortsätt uttryckligen eller stoppa och spara." },
    STOPPING: { tone: "warning", title: "Stoppar och fryser spåret", detail: "Vänta på lokal kvittens innan du lämnar appen." },
    STOPPED: { tone: "neutral", title: "Spåret är sparat på telefonen", detail: "Versionen är fryst men inte synkad. Avinstallera inte appen om spåret ska bevaras." },
    PERMISSION_REQUIRED: { tone: "warning", title: "Exakt platsbehörighet krävs", detail: "Ge appen precis platsåtkomst för att kunna spela in ett orienteringsspår." },
    NOTIFICATION_REQUIRED: { tone: "warning", title: "Notiser behöver tillåtas", detail: "Tillåt inspelningsnotisen så att aktiv GPS är tydlig även när appen inte syns." },
    LOCATION_OFF: { tone: "warning", title: "Plats är avstängd", detail: "Slå på telefonens platstjänst och prova igen." },
    STORAGE_ERROR: { tone: "error", title: "Lagringen avbröt inspelningen", detail: "Inga nya punkter sparas. Behåll appen installerad och granska den lokala versionen." },
    SERVICE_ERROR: { tone: "error", title: "GPS-tjänsten kunde inte köras", detail: "Ingen inspelning ska antas pågå. Uppdatera status innan du försöker igen." },
    UNAVAILABLE: { tone: "warning", title: "GPS-inspelning kräver Androidappen", detail: "Den här utvecklarversionen spelar inte in GPS i browsern. Publika resultat finns separat utan app." }
  },
  actionFailed: "Åtgärden misslyckades. Ingen ny inspelning bekräftas.",
  actionPending: "Väntar på Androidtjänsten…",
  statusFailed: "GPS-tillståndet kunde inte läsas. Anta inte att inspelning pågår.",
  networkOnline: "Ansluten enligt telefonen",
  networkOffline: "Offline enligt telefonen",
  noMeasurement: "Ingen punkt ännu",
  localVersionPrefix: "Lokal ",
  noVersion: "Ingen version"
} as const;
