export const checkinRosterText = {
  title: "Avprickningslista",
  classFilter: "Klassfilter",
  allClasses: "Alla klasser",
  shown: "Visar",
  of: "av",
  writing: "Aktivera skrivläge",
  writingHelp: "Skrivläge måste aktiveras uttryckligen innan en lokal markering kan sparas.",
  writingOn: "Skrivläge är aktivt.",
  writingOff: "Skrivläge är avstängt.",
  name: "Namn",
  club: "Klubb",
  noClub: "Ingen klubb angiven",
  card: "Bricka",
  noCard: "Ingen bricka angiven",
  multipleCards: "Flera aktiva brickkopplingar – kontrollera",
  plannedStart: "Planerad start",
  freeStart: "Fri start",
  serverStart: "Serverns startmarkering",
  localIntent: "Lokalt sparad avsikt",
  className: "Klass",
  localKnowledge: "Lokala avsikter är inte officiella starttider, DNS-beslut eller resultat. Väntande poster är inte servergenomförda och konflikter är inte applicerade.",
  pending: "Väntar på serverkvittens",
  conflicts: "Konflikter att kontrollera",
  reviewedConflicts: "Granskade konfliktrapporter – originalkvittensen bevarad",
  historicalConflict: "Historiska motstridiga uppgifter finns kvar och måste kontrolleras.",
  startStates: {
    UNMARKED: "Omarkerad",
    STARTED: "Startat",
    REPORTED_NOT_STARTED: "Uppgiven ej start"
  },
  startActions: {
    UNMARKED: "Markera omarkerad",
    STARTED: "Markera startat",
    REPORTED_NOT_STARTED: "Markera uppgiven ej start"
  },
  startSave: "Spara startmarkering",
  manualReturn: "Manuell återkomst registrerad",
  finishState: "Startmarkering",
  finishSave: "Spara målkorrektion",
  noEntries: "Inga deltagare i valt urval.",
  print: "Skriv ut aktuellt startunderlag",
  printTitle: "Privat pappersunderlag för start",
  printHelp: "Planerade starter från den lokala listan. Pappersnoteringar förs inte över till systemet.",
  printBasis: "Lokalt rosterunderlag",
  printFilter: "Urval",
  printPaperMark: "Pappersnotering"
} as const;
