export const checkinText = {
  title: "O-Tid – start och mål",
  openMobile: "Öppna privat avprickning för start och mål",
  shellLabel: "Offline-appskal",
  subtitle: "Privat avprickning på den här mobilen.",
  shellMissing: "Appskalet är ännu inte förberett för offline.",
  shellReady: "Appskal kontrollerat:",
  shellFailed: "Appskalet kunde inte förberedas. Behåll nätanslutningen och försök igen.",
  prepareShell: "Förbered offline-appskal",
  prepare: "Förbered privat startlista", unlock: "Lås upp lokal lista", lock: "Lås lokal lista",
  race: "Loppets interna id", capability: "Arbetsuppgift", start: "Startpersonal", finish: "Målpersonal",
  label: "Mobilens namn", credential: "Personlig arbetsbehörighet", passphrase: "Separat lokal lösenfras (minst 16 tecken)",
  consent: "Jag godkänner att den privata listan och markeringarna sparas krypterat på denna mobil.",
  persist: "Kontrollera beständig lagring", persisted: "Webbläsaren har beviljat beständig lagring.",
  notPersisted: "Webbläsaren har inte beviljat beständig lagring. Lokala data kan rensas vid lagringsbrist.",
  risk: "Jag accepterar den risken och har en reservrutin för avprickning.",
  secretWarning: "Lösenfrasen skickas inte till servern. Bevara den separat; den kan inte återställas. Använd en betrodd mobil med enhetslås.",
  localList: "Sparad lokal lista", none: "Ingen lokal lista finns på denna browserprofil.",
  saved: "Privat lista sparad och återläst lokalt. Den beskriver endast senast hämtad kunskap.",
  unlocked: "Lokalt upplåst. Detta ger inte ny serverbehörighet.",
  failed: "Åtgärden misslyckades. Inga befintliga lokala markeringar har raderats. Kontrollera behörighet, lösenfras, nät och lagringsutrymme.",
  locked: "Listan är låst. Lokala data och kö behålls.",
  pending: "Väntar lokalt:", version: "Tävlingsversion:", generated: "Underlag hämtat:",
  readOnly: "Skrivknappar och synk från denna vy är ännu inte aktiverade.",
  noHardware: "Hårdvara: manuell lista, ingen SPORTident-koppling.",
  markSaved: "Markeringen är sparad lokalt. Se köstatus för serverns kvittens.",
  operationStatus: "Avprickning och synk",
  sync: "Synka väntande markeringar", loginSync: "Logga in och synka med samma arbetsbehörighet",
  autoSync: "Synka automatiskt när nätet återkommer medan listan är upplåst",
  clearTitle: "Avsluta och rensa denna lokala lista",
  clearConsent: "Jag vill radera denna mobils lokala lista och kvitterade historik. Serverns historik behålls. Åtgärden kan inte ångras lokalt.",
  clear: "Rensa bekräftat färdig lokal lista",
  cleared: "Den lokala listan och dess kvitterade historik har raderats från denna webbläsare. Serverhistoriken är kvar; lokal radering kan inte ångras.",
  clearFailed: "Rensningen kunde inte bekräftas. Läs om den lokala listan. Okvitterade poster, ogranskade konflikter eller en ändrad lokal version hindrar rensning.",
  synced: "Synk klar. Kontrollera kvarvarande kö och konflikter; en konflikt är inte en genomförd ändring.",
  syncStopped: "Synken stoppades. Kön behålls. Kontrollera nätet och logga vid behov in med samma arbetsbehörighet. En spärrad eller utgången behörighet kräver hjälp av arrangören.",
  staleLocal: "Listan ändrades i en annan flik. Den har lästs om och skrivläget stängts av. Granska innan du försöker igen.",
  review: "Konflikten behöver granskas. Ingen ny markering skapades.",
  refreshLocal: "Läs om lokal lista",
  recoveryExport: "Exportera privat återhämtningsunderlag",
  recoveryExported: "Återhämtningsunderlaget har exporterats. Originalkön är oförändrad. Underlaget ger ingen skrivbehörighet.",
  recoveryHelp: "Vid spärrad eller utgången arbetsbehörighet: bevara mobilen och lämna det privata återhämtningsunderlaget säkert till ansvarig arrangör. Arrangören kan ge en tillfällig behörighet för exakt de bevarade markeringarna. Den ger inte rätt att arbeta vidare eller hämta en ny lista.",
  recoveryTitle: "Återför bevarad kö med arrangörens hjälp",
  recoveryToken: "Tillfällig återhämtningsbehörighet",
  recoveryConsent: "Jag vill återföra den bevarade kön. Konflikter ska behållas för granskning och originalmarkeringarna får inte ändras.",
  recoverySubmit: "Återför bevarade markeringar",
  recoverySynced: "Återföringen är kvitterad och sparad lokalt. Kontrollera kvarvarande konflikter. Listunderlaget har inte uppdaterats och den gamla arbetsbehörigheten är fortfarande ogiltig.",
  recoveryStopped: "Återföringen stoppades. Bevarade markeringar och mottagna kvittenser finns kvar. Kontrollera nät och tillfällig behörighet med arrangören och försök igen. Inga markeringar ombaseras automatiskt.",
  offline: "Internet: browsern rapporterar offline.", online: "Internet: browsern rapporterar nät. Serverkontakt är inte garanterad."
} as const;
