plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace = 'se.otid.station.store'
    compileSdk = rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk = rootProject.ext.minSdkVersion
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
        freeCompilerArgs += ['-Xjsr305=strict']
    }

    testOptions {
        unitTests.returnDefaultValues = false
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation "androidx.core:core:$androidxCoreVersion"

    testImplementation "junit:junit:$junitVersion"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlinVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
}
