import { authenticatePairingAdminSession, decideDidNotFinishAsAdmin, listDidNotFinishCandidatesAsAdmin, loginPairingAdmin, logoutPairingAdminSession } from "@o-tid/application";
import { didNotFinishAdminLoginRequestSchema, didNotFinishAdminLoginResponseSchema, didNotFinishCandidateResponseSchema, didNotFinishIdempotencyKeySchema, didNotFinishRequestSchema, didNotFinishResponseSchema } from "@o-tid/contracts";
import type { Database } from "@o-tid/database";
import { DidNotFinishAdminConfigurationError, clearDidNotFinishAdminCookies, didNotFinishAdminFailure, didNotFinishAdminJson, didNotFinishAdminSecurityPolicy, didNotFinishAdminSessionProof, hasExpectedDidNotFinishAdminOrigin, hasNoDidNotFinishAdminRequestBody, privateDidNotFinishAdminHeaders, readDidNotFinishAdminJson, setDidNotFinishAdminCookies } from "./did-not-finish-admin-security";

type Environment = Partial<Pick<NodeJS.ProcessEnv, "NODE_ENV" | "O_TID_PUBLIC_ORIGIN">>;
type Login = typeof loginPairingAdmin; type Authenticate = typeof authenticatePairingAdminSession;
type Logout = typeof logoutPairingAdminSession; type List = typeof listDidNotFinishCandidatesAsAdmin; type Decide = typeof decideDidNotFinishAsAdmin;

function policyOrFailure(environment: Environment) { try { return { policy: didNotFinishAdminSecurityPolicy(environment) } as const; } catch (error) { if (error instanceof DidNotFinishAdminConfigurationError) return { response: didNotFinishAdminFailure(500, "INTERNAL_ERROR") } as const; throw error; } }
function invalidLoginStatus(value: unknown): 400 | 401 { if (typeof value !== "object" || value === null || Array.isArray(value)) return 400; const record = value as Record<string, unknown>; const keys = Object.keys(record).sort(); return keys.length === 2 && keys[0] === "accessCredential" && keys[1] === "formatVersion" && record.formatVersion === 1 && typeof record.accessCredential === "string" ? 401 : 400; }
function applicationFailure(result: { status: string }): Response | undefined { if (result.status === "invalid-request") return didNotFinishAdminFailure(400, "INVALID_REQUEST"); if (result.status === "unauthorized") return didNotFinishAdminFailure(401, "UNAUTHORIZED"); if (result.status === "forbidden") return didNotFinishAdminFailure(403, "FORBIDDEN"); if (result.status === "not-found") return didNotFinishAdminFailure(404, "NOT_FOUND"); if (result.status === "conflict") return didNotFinishAdminFailure(409, "CONFLICT"); return undefined; }

export async function didNotFinishAdminLoginRoute(db: Database, request: Request, raceId: string, login: Login = loginPairingAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response;
  if (!hasExpectedDidNotFinishAdminOrigin(request, configured.policy)) return didNotFinishAdminFailure(403, "FORBIDDEN");
  let body: unknown; try { body = await readDidNotFinishAdminJson(request); } catch { return didNotFinishAdminFailure(400, "INVALID_REQUEST"); }
  const parsed = didNotFinishAdminLoginRequestSchema.safeParse(body); if (!parsed.success) { const status = invalidLoginStatus(body); return didNotFinishAdminFailure(status, status === 401 ? "UNAUTHORIZED" : "INVALID_REQUEST"); }
  try { const result = await login(db, parsed.data, { expectedRaceId: raceId, expectedCapability: "DECIDE_DID_NOT_FINISH" }); if (result.status === "unauthorized") return didNotFinishAdminFailure(401, "UNAUTHORIZED"); const response = didNotFinishAdminLoginResponseSchema.parse(result.response); return setDidNotFinishAdminCookies(didNotFinishAdminJson(response), configured.policy, { sessionToken: result.sessionToken, csrfToken: result.csrfToken, expiresAt: response.expiresAt }); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function didNotFinishAdminSessionStatusRoute(db: Database, request: Request, raceId: string, authenticate: Authenticate = authenticatePairingAdminSession, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; const proof = didNotFinishAdminSessionProof(request, configured.policy, false);
  try { const result = await authenticate(db, { ...proof, raceId, capability: "DECIDE_DID_NOT_FINISH" }); if (result.status === "unauthorized") return didNotFinishAdminFailure(401, "UNAUTHORIZED"); if (result.status === "forbidden") return didNotFinishAdminFailure(403, "FORBIDDEN"); return didNotFinishAdminJson(didNotFinishAdminLoginResponseSchema.parse({ formatVersion: 1, raceId: result.principal.raceId, capability: result.principal.capability, expiresAt: result.principal.expiresAt })); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function didNotFinishAdminLogoutRoute(db: Database, request: Request, raceId: string, logout: Logout = logoutPairingAdminSession, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; if (!hasExpectedDidNotFinishAdminOrigin(request, configured.policy)) return didNotFinishAdminFailure(403, "FORBIDDEN"); const proof = didNotFinishAdminSessionProof(request, configured.policy, true);
  try { const result = await logout(db, { ...proof, raceId, capability: "DECIDE_DID_NOT_FINISH", readBodyIsEmpty: () => hasNoDidNotFinishAdminRequestBody(request) }); if (result.status === "unauthorized") return clearDidNotFinishAdminCookies(didNotFinishAdminFailure(401, "UNAUTHORIZED"), configured.policy); if (result.status === "forbidden") return didNotFinishAdminFailure(403, "FORBIDDEN"); if (result.status === "invalid-request") return didNotFinishAdminFailure(400, "INVALID_REQUEST"); return clearDidNotFinishAdminCookies(new Response(null, { status: 204, headers: privateDidNotFinishAdminHeaders }), configured.policy); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function didNotFinishCandidateListRoute(db: Database, request: Request, raceId: string, list: List = listDidNotFinishCandidatesAsAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; const proof = didNotFinishAdminSessionProof(request, configured.policy, false);
  try { const result = await list(db, { ...proof, raceId }); const failure = applicationFailure(result); if (failure) return failure; if (!("response" in result)) return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); return didNotFinishAdminJson(didNotFinishCandidateResponseSchema.parse(result.response)); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function authenticatedDidNotFinishRoute(db: Database, request: Request, raceId: string, entryId: string, authenticate: Authenticate = authenticatePairingAdminSession, decide: Decide = decideDidNotFinishAsAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; if (!hasExpectedDidNotFinishAdminOrigin(request, configured.policy)) return didNotFinishAdminFailure(403, "FORBIDDEN"); const proof = didNotFinishAdminSessionProof(request, configured.policy, true);
  try { const authorization = await authenticate(db, { ...proof, raceId, capability: "DECIDE_DID_NOT_FINISH", requireCsrf: true }); if (authorization.status === "unauthorized") return didNotFinishAdminFailure(401, "UNAUTHORIZED"); if (authorization.status === "forbidden") return didNotFinishAdminFailure(403, "FORBIDDEN"); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
  const idempotencyKey = request.headers.get("idempotency-key"); if (!didNotFinishIdempotencyKeySchema.safeParse(idempotencyKey).success) return didNotFinishAdminFailure(400, "INVALID_REQUEST");
  let body: unknown; try { body = await readDidNotFinishAdminJson(request); } catch { return didNotFinishAdminFailure(400, "INVALID_REQUEST"); } const parsed = didNotFinishRequestSchema.safeParse(body); if (!parsed.success) return didNotFinishAdminFailure(400, "INVALID_REQUEST");
  try { const result = await decide(db, { ...proof, raceId, entryId, idempotencyKey, request: parsed.data }); const failure = applicationFailure(result); if (failure) return failure; if (!("response" in result)) return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); return didNotFinishAdminJson(didNotFinishResponseSchema.parse(result.response)); } catch { return didNotFinishAdminFailure(500, "INTERNAL_ERROR"); }
}
