import { describe, expect, it, vi } from "vitest";
import type { authenticatePairingAdminSession, withdrawOutOfCompetitionAsAdmin } from "@o-tid/application";
import type { Database } from "@o-tid/database";
import { authenticatedOutOfCompetitionWithdrawalRoute } from "./out-of-competition-withdrawal-admin-route-handlers";

const db = {} as Database; const raceId = "10000000-0000-4000-8000-000000000001"; const entryId = "10000000-0000-4000-8000-000000000002"; const classId = "10000000-0000-4000-8000-000000000003"; const courseVersionId = "10000000-0000-4000-8000-000000000004"; const requestId = "10000000-0000-4000-8000-000000000005"; const targetId = "10000000-0000-4000-8000-000000000006"; const oocId = "10000000-0000-4000-8000-000000000007"; const decisionId = "10000000-0000-4000-8000-000000000008"; const withdrawalId = "10000000-0000-4000-8000-000000000009"; const restorationId = "10000000-0000-4000-8000-00000000000a"; const csrf = "c".repeat(43); const environment = { NODE_ENV: "production", O_TID_PUBLIC_ORIGIN: "https://otid.example" } as const;
const body = { formatVersion: 1 as const, expectedEntryVersion: 2, expectedClassId: classId, expectedCourseVersionId: courseVersionId, expectedSnapshotVersion: 4, expectedNotCompetingDecisionId: decisionId, expectedTargetResultRevision: { id: targetId, revision: 3 }, expectedOutOfCompetitionResultRevision: { id: oocId, revision: 4 }, expectedAbsoluteResultRevision: { id: oocId, revision: 4 }, expectedRestorationSourceResultRevision: { id: targetId, revision: 3, status: "MP" as const, reason: "MISSING_CONTROL" as const, cause: "CARD_READOUT" as const }, reason: "ERRONEOUS_MANUAL_OUT_OF_COMPETITION" as const, policyVersion: "out-of-competition-withdrawal-v1" as const };
const authenticated = () => ({ status: "authenticated" as const, principal: { accessCredentialId: requestId, raceId, capability: "WITHDRAW_OUT_OF_COMPETITION" as const, sessionId: requestId, expiresAt: "2026-09-01T13:00:00.000Z" } });

describe("TASK 006L OOC-återtagningsroutes", () => {
  it("avvisar fel origin och idempotensnyckel före bodyläsning", async () => { let reads = 0; const unread = { headers: new Headers({ origin: "https://evil.example" }), body: { getReader() { reads += 1; throw new Error("body lästes"); } } } as unknown as Request; expect((await authenticatedOutOfCompetitionWithdrawalRoute(db, unread, raceId, entryId, vi.fn() as unknown as typeof authenticatePairingAdminSession, vi.fn() as unknown as typeof withdrawOutOfCompetitionAsAdmin, environment)).status).toBe(403); expect(reads).toBe(0); const badKey = { headers: new Headers({ origin: environment.O_TID_PUBLIC_ORIGIN, cookie: `__Host-otid-out-of-competition-withdrawal-admin-session=x; __Host-otid-out-of-competition-withdrawal-admin-csrf=${csrf}`, "x-otid-csrf": csrf, "idempotency-key": "bad" }), body: { getReader() { reads += 1; throw new Error("body lästes"); } } } as unknown as Request; expect((await authenticatedOutOfCompetitionWithdrawalRoute(db, badKey, raceId, entryId, vi.fn(async () => authenticated()) as unknown as typeof authenticatePairingAdminSession, vi.fn() as unknown as typeof withdrawOutOfCompetitionAsAdmin, environment)).status).toBe(400); expect(reads).toBe(0); });
  it("vidarebefordrar komplett fryst OOC-withdrawal-intent", async () => { const withdraw = vi.fn(async () => ({ status: "withdrawn" as const, response: { formatVersion: 1 as const, replayed: false, requestId, raceId, entryId, outOfCompetitionWithdrawalId: withdrawalId, notCompetingDecisionId: decisionId, outOfCompetitionResultRevisionId: oocId, restorationSourceResultRevisionId: targetId, restorationResultRevisionId: restorationId, revision: 5, cause: "MANUAL_OUT_OF_COMPETITION_WITHDRAWAL" as const, status: "MP" as const, reason: "MISSING_CONTROL" as const, withdrawalReason: "ERRONEOUS_MANUAL_OUT_OF_COMPETITION" as const, policyVersion: "out-of-competition-withdrawal-v1" as const, snapshotVersion: 4, courseVersionId, withdrawnAt: "2026-09-01T11:00:00.000Z" } })) as unknown as typeof withdrawOutOfCompetitionAsAdmin; const response = await authenticatedOutOfCompetitionWithdrawalRoute(db, new Request("https://otid.example", { method: "POST", headers: { origin: environment.O_TID_PUBLIC_ORIGIN, cookie: `__Host-otid-out-of-competition-withdrawal-admin-session=x; __Host-otid-out-of-competition-withdrawal-admin-csrf=${csrf}`, "x-otid-csrf": csrf, "content-type": "application/json", "idempotency-key": `out-of-competition-withdrawal:${requestId}` }, body: JSON.stringify(body) }), raceId, entryId, vi.fn(async () => authenticated()) as unknown as typeof authenticatePairingAdminSession, withdraw, environment); expect(response.status).toBe(200); expect(withdraw).toHaveBeenCalledWith(db, expect.objectContaining({ raceId, entryId, idempotencyKey: `out-of-competition-withdrawal:${requestId}`, request: body })); });
});
