import { authenticatePairingAdminSession, decideOutOfCompetitionAsAdmin, listOutOfCompetitionCandidatesAsAdmin, loginPairingAdmin, logoutPairingAdminSession } from "@o-tid/application";
import { outOfCompetitionAdminLoginRequestSchema, outOfCompetitionAdminLoginResponseSchema, outOfCompetitionCandidateResponseSchema, outOfCompetitionIdempotencyKeySchema, outOfCompetitionRequestSchema, outOfCompetitionResponseSchema } from "@o-tid/contracts";
import type { Database } from "@o-tid/database";
import { OutOfCompetitionAdminConfigurationError, clearOutOfCompetitionAdminCookies, hasExpectedOutOfCompetitionAdminOrigin, hasNoOutOfCompetitionAdminRequestBody, outOfCompetitionAdminFailure, outOfCompetitionAdminJson, outOfCompetitionAdminSecurityPolicy, outOfCompetitionAdminSessionProof, privateOutOfCompetitionAdminHeaders, readOutOfCompetitionAdminJson, setOutOfCompetitionAdminCookies } from "./out-of-competition-admin-security";

type Environment = Partial<Pick<NodeJS.ProcessEnv, "NODE_ENV" | "O_TID_PUBLIC_ORIGIN">>;
type Login = typeof loginPairingAdmin; type Authenticate = typeof authenticatePairingAdminSession;
type Logout = typeof logoutPairingAdminSession; type List = typeof listOutOfCompetitionCandidatesAsAdmin; type Decide = typeof decideOutOfCompetitionAsAdmin;

function policyOrFailure(environment: Environment) { try { return { policy: outOfCompetitionAdminSecurityPolicy(environment) } as const; } catch (error) { if (error instanceof OutOfCompetitionAdminConfigurationError) return { response: outOfCompetitionAdminFailure(500, "INTERNAL_ERROR") } as const; throw error; } }
function invalidLoginStatus(value: unknown): 400 | 401 { if (typeof value !== "object" || value === null || Array.isArray(value)) return 400; const record = value as Record<string, unknown>; const keys = Object.keys(record).sort(); return keys.length === 2 && keys[0] === "accessCredential" && keys[1] === "formatVersion" && record.formatVersion === 1 && typeof record.accessCredential === "string" ? 401 : 400; }
function applicationFailure(result: { status: string }): Response | undefined { if (result.status === "invalid-request") return outOfCompetitionAdminFailure(400, "INVALID_REQUEST"); if (result.status === "unauthorized") return outOfCompetitionAdminFailure(401, "UNAUTHORIZED"); if (result.status === "forbidden") return outOfCompetitionAdminFailure(403, "FORBIDDEN"); if (result.status === "not-found") return outOfCompetitionAdminFailure(404, "NOT_FOUND"); if (result.status === "conflict") return outOfCompetitionAdminFailure(409, "CONFLICT"); return undefined; }

export async function outOfCompetitionAdminLoginRoute(db: Database, request: Request, raceId: string, login: Login = loginPairingAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response;
  if (!hasExpectedOutOfCompetitionAdminOrigin(request, configured.policy)) return outOfCompetitionAdminFailure(403, "FORBIDDEN");
  let body: unknown; try { body = await readOutOfCompetitionAdminJson(request); } catch { return outOfCompetitionAdminFailure(400, "INVALID_REQUEST"); }
  const parsed = outOfCompetitionAdminLoginRequestSchema.safeParse(body); if (!parsed.success) { const status = invalidLoginStatus(body); return outOfCompetitionAdminFailure(status, status === 401 ? "UNAUTHORIZED" : "INVALID_REQUEST"); }
  try { const result = await login(db, parsed.data, { expectedRaceId: raceId, expectedCapability: "DECIDE_OUT_OF_COMPETITION" }); if (result.status === "unauthorized") return outOfCompetitionAdminFailure(401, "UNAUTHORIZED"); const response = outOfCompetitionAdminLoginResponseSchema.parse(result.response); return setOutOfCompetitionAdminCookies(outOfCompetitionAdminJson(response), configured.policy, { sessionToken: result.sessionToken, csrfToken: result.csrfToken, expiresAt: response.expiresAt }); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function outOfCompetitionAdminSessionStatusRoute(db: Database, request: Request, raceId: string, authenticate: Authenticate = authenticatePairingAdminSession, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; const proof = outOfCompetitionAdminSessionProof(request, configured.policy, false);
  try { const result = await authenticate(db, { ...proof, raceId, capability: "DECIDE_OUT_OF_COMPETITION" }); if (result.status === "unauthorized") return outOfCompetitionAdminFailure(401, "UNAUTHORIZED"); if (result.status === "forbidden") return outOfCompetitionAdminFailure(403, "FORBIDDEN"); return outOfCompetitionAdminJson(outOfCompetitionAdminLoginResponseSchema.parse({ formatVersion: 1, raceId: result.principal.raceId, capability: result.principal.capability, expiresAt: result.principal.expiresAt })); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function outOfCompetitionAdminLogoutRoute(db: Database, request: Request, raceId: string, logout: Logout = logoutPairingAdminSession, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; if (!hasExpectedOutOfCompetitionAdminOrigin(request, configured.policy)) return outOfCompetitionAdminFailure(403, "FORBIDDEN"); const proof = outOfCompetitionAdminSessionProof(request, configured.policy, true);
  try { const result = await logout(db, { ...proof, raceId, capability: "DECIDE_OUT_OF_COMPETITION", readBodyIsEmpty: () => hasNoOutOfCompetitionAdminRequestBody(request) }); if (result.status === "unauthorized") return clearOutOfCompetitionAdminCookies(outOfCompetitionAdminFailure(401, "UNAUTHORIZED"), configured.policy); if (result.status === "forbidden") return outOfCompetitionAdminFailure(403, "FORBIDDEN"); if (result.status === "invalid-request") return outOfCompetitionAdminFailure(400, "INVALID_REQUEST"); return clearOutOfCompetitionAdminCookies(new Response(null, { status: 204, headers: privateOutOfCompetitionAdminHeaders }), configured.policy); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function outOfCompetitionCandidateListRoute(db: Database, request: Request, raceId: string, list: List = listOutOfCompetitionCandidatesAsAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; const proof = outOfCompetitionAdminSessionProof(request, configured.policy, false);
  try { const result = await list(db, { ...proof, raceId }); const failure = applicationFailure(result); if (failure) return failure; if (!("response" in result)) return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); return outOfCompetitionAdminJson(outOfCompetitionCandidateResponseSchema.parse(result.response)); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
}

export async function authenticatedOutOfCompetitionRoute(db: Database, request: Request, raceId: string, entryId: string, authenticate: Authenticate = authenticatePairingAdminSession, decide: Decide = decideOutOfCompetitionAsAdmin, environment: Environment = process.env): Promise<Response> {
  const configured = policyOrFailure(environment); if ("response" in configured) return configured.response; if (!hasExpectedOutOfCompetitionAdminOrigin(request, configured.policy)) return outOfCompetitionAdminFailure(403, "FORBIDDEN"); const proof = outOfCompetitionAdminSessionProof(request, configured.policy, true);
  try { const authorization = await authenticate(db, { ...proof, raceId, capability: "DECIDE_OUT_OF_COMPETITION", requireCsrf: true }); if (authorization.status === "unauthorized") return outOfCompetitionAdminFailure(401, "UNAUTHORIZED"); if (authorization.status === "forbidden") return outOfCompetitionAdminFailure(403, "FORBIDDEN"); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
  const idempotencyKey = request.headers.get("idempotency-key"); if (!outOfCompetitionIdempotencyKeySchema.safeParse(idempotencyKey).success) return outOfCompetitionAdminFailure(400, "INVALID_REQUEST");
  let body: unknown; try { body = await readOutOfCompetitionAdminJson(request); } catch { return outOfCompetitionAdminFailure(400, "INVALID_REQUEST"); } const parsed = outOfCompetitionRequestSchema.safeParse(body); if (!parsed.success) return outOfCompetitionAdminFailure(400, "INVALID_REQUEST");
  try { const result = await decide(db, { ...proof, raceId, entryId, idempotencyKey, request: parsed.data }); const failure = applicationFailure(result); if (failure) return failure; if (!("response" in result)) return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); return outOfCompetitionAdminJson(outOfCompetitionResponseSchema.parse(result.response)); } catch { return outOfCompetitionAdminFailure(500, "INTERNAL_ERROR"); }
}
